### ISSUE TITLE
Meaning of metadata internal file

### ISSUE THREAD

**Issue by zsw111-zzz** [GeWu-Lab/MWAFM#2]
Thanks a lot for your great contribution, but I'm having some issues reproducing your work. For the metadata part in the code base, does the source data contained inside come from the Clotho-AQA dataset or the AQA-MUSIC-AVQA dataset? Do the files starting with single_word, binary_test, clothho_aqa and other flags have any special meaning? Looking forward to your reply, thank you again!

**Comment by zsw111-zzz** [comment]
Your reply perfectly solved my problem, thank you very much for your reply！

**Comment by ayameyao** [comment]
We examined the original annotation files of Clotho-AQA and found that the official open-source annotations were not cleansed, resulting in discrepancies where different annotators provided different answers for the same question. As a result, we performed a simple filtering process where we considered a question to have the correct answer if it had at least two identical answers Based on this filtering process, we obtained a new and more accurate annotation file. The files in 'metadata' folder are described as follows

- 'single_word\_[train/val/test].csv', Does not contain samples with answers *yes* and *no*.
- 'single_word\_[train/val/test]\_clean.csv', Does not contain samples with answers *yes* and *no*. (Cleaned data)
- 'clotho_aqa\_[train/val/test]\_clean.csv', Contains samples with answers *yes* and *no*. (Cleaned data)
- 'binary\_[train/val/test]\_clean.csv', Include only samples with answers *yes* and *no*. (Cleaned data)

We have updated the detailed description in the 'readme.md' file, please check it.

**Comment by zsw111-zzz** [comment]
Your reply perfectly solved my problem, thank you very much for your reply！
