### ISSUE TITLE
Meta files of Audio-MUSIC-AVQA

### ISSUE THREAD

**Issue by JustinYuu** [GeWu-Lab/MWAFM#3]
Hi Guangyao,

Thanks for your great work! It seems that the folder metadata/ only contains annotations of ClothoAQA. Could you please share the annotation files of Audio-MUSIC-AVQA?

**Comment by ayameyao** [comment]
Hi, 
We welcome your interest in our work! 
Audio-MUSIC-AVQA is a subset of MUSIC-AVQA. Specifically, it only uses the Audio category questions in MUSIC-AVQA. link: https://github.com/GeWu-Lab/MUSIC-AVQA/tree/main/data
If you have more questions, please do not hesitate to contact me directly via email: guangyaoli@ruc.edu.cn

best,
guangyao

**Comment by JustinYuu** [comment]
Many thanks!
